# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev1',
                'doc_host': 'https://adamaslan.github.io',
                'git_url': 'https://github.com/adamaslan/nbdev1',
                'lib_path': 'nbdev1'},
  'syms': {'nbdev1.core': {'nbdev1.core.foo': ('core.html#foo', 'nbdev1/core.py')}}}
