project:
  type: website

format:
  html:
    theme: solar
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Blog"  # New link for blog
        href: /blog/  # Link points to blog 
    right:
      - text: "About"  # New link for about.qmd
        file: about.qmd
    # sidebar: 
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]